
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-netflix-fe
  labels:
    app: nginx-netflix-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-netflix-fe
  template:
    metadata:
      labels:
        app: nginx-netflix-fe
    spec:
      containers:
        - name: nginx-netflix-fe
          image: alonithuji/netflix-frontend:0.0.1
          env:
            - name: MOVIE_CATALOG_SERVICE
              value: "http://nginx-service:8080"
            - name: REDIS_URL
              value: "redis:6379"

